import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-college-list',
  templateUrl: './college-list.component.html',
  styleUrls: ['./college-list.component.scss']
})
export class CollegeListComponent implements OnInit {

  collegeList = {
    "United Kingdom": [
      { id: 1, name: "Anglia Ruskin University" },
      { id: 2, name: "Arts University Bournemouth" },
      { id: 3, name: "Aston University" },
      { id: 4, name: "Bangor University" },
      { id: 5, name: "Birmingham City University" },
      { id: 6, name: "BPP University" },
      { id: 7, name: "BPP University" },
      { id: 8, name: "Brunel University" },
      { id: 9, name: "Cardi? Metropolitan University" },
      { id: 10, name: "Cran?eld University" },
      { id: 11, name: "Coventry University" },
      { id: 12, name: "Durham University" },
      { id: 13, name: "Glasgow Caledonian University" },
      { id: 14, name: "Heriot Watt University" },
      { id: 15, name: "Navitas" },
      { id: 16, name: "Hult International Business School" },
      { id: 17, name: "Glasgow Caledonian University" },
      { id: 18, name: "Newcastle University" },
      { id: 19, name: "University of East Anglia" },
      { id: 20, name: "University of Exeter" },
      { id: 21, name: "University of Manchester" },
      { id: 22, name: "Istituto Marangoni" },
      { id: 23, name: "Kaplan International Colleges" },
      { id: 24, name: "Keele University" },
      { id: 25, name: "Kingston University" },
      { id: 26, name: "Leeds Arts University" },
      { id: 27, name: "Leeds Beckett University" },
      { id: 28, name: "LIBT(in association with Brunel University)" },
      { id: 29, name: "Liverpool John Moores University" },
      { id: 30, name: "London South Bank University" },
      { id: 31, name: "Middlesex University" },
      { id: 32, name: "Newcastle University" },
      { id: 33, name: "Northumbria University" },
      { id: 34, name: "Norwich University of the Arts" },
      { id: 35, name: "Oxford Brookes University" },
      { id: 36, name: "Queen Margaret University" },
      { id: 37, name: "Queen Mary University of London" },
      { id: 38, name: "Queen s University Belfast" },
      { id: 39, name: "Queen s University Belfast" },
      { id: 40, name: "Queen s University Belfast" },
      { id: 41, name: "Regent s College London" },
      { id: 42, name: "Robert Gordon University" },
      { id: 43, name: "Solent University Southampton" },
      { id: 44, name: "St Mary’s University" },
      { id: 45, name: "Sta?ordshire University" },
      { id: 46, name: "The University of Law" },
      { id: 47, name: "Teesside University" },
      { id: 48, name: "University of Abertay Dundee" },
      { id: 49, name: "University of Bedfordshire" },
      { id: 50, name: "University of Bolton" },
      { id: 51, name: "University of Bradford" },
      { id: 52, name: "University of Brighton" },
      { id: 53, name: "University of Buckingham" },
      { id: 54, name: "University of Central Lancashire" },
      { id: 55, name: "University of Chester" },
      { id: 56, name: "University of Chichester" },
      { id: 57, name: "University of Derby" },
      { id: 58, name: "University of Dundee" },
      { id: 59, name: "University of East London" },
      { id: 60, name: "University of South Wales" },
      { id: 61, name: "University of Glasgow" },
      { id: 62, name: "University of Gloucestershire" },
      { id: 63, name: "University of Greenwich" },
      { id: 64, name: "University of Hertfordshire" },
      { id: 65, name: "University of Hudders?eld" },
      { id: 66, name: "University of Kent" },
      { id: 67, name: "University of Leeds" },
      { id: 68, name: "University of Leicester" },
      { id: 69, name: "University of Lincoln" },
      { id: 70, name: "University of Plymouth" },
      { id: 71, name: "University of Reading" },
      { id: 72, name: "University of Roehampton" },
      { id: 73, name: "University Of Salford" },
      { id: 74, name: "University of Strathclyde" },
      { id: 75, name: "University of Sunderland London Campus" },
      { id: 76, name: "University of Sussex" },
      { id: 77, name: "University of Wales Trinity Saint David" },
      { id: 78, name: "University of the West England" },
      { id: 79, name: "University of West London" },
      { id: 80, name: "University of Westminster" },
      { id: 81, name: "UWS (University of West of Scotland London Campus)" },
      { id: 82, name: "University of Wolverhampton" },
      { id: 83, name: "coventry" },
    ],
    "Canada": [
      { id: 1, name: "Arts University Bournemouth" },
      { id: 2, name: "Canada College" },
      { id: 3, name: "Acsenda School of Management" },
      { id: 4, name: "Toronto School of Management" },
      { id: 5, name: "University of Lethbridge" },
      { id: 6, name: "University of Northern British Columbia" },
      { id: 7, name: "Vancouver Film School" },
      { id: 8, name: "University Canada West" },
      { id: 9, name: "University of Windsor" },
      { id: 10, name: "Vancouver Community College" },
      { id: 11, name: "University of Alberta" },
      { id: 12, name: "Toronto Film School" },
      { id: 13, name: "ABC Access Business College" },
      { id: 14, name: "Academy of Applied Pharmaceutical Sciences" },
      { id: 15, name: "Acadia University" },
      { id: 16, name: "ACCESS Adult Education & Career Training Centre" },
      { id: 17, name: "Acsenda School of Management" },
      { id: 18, name: "Alexander College" },
      { id: 19, name: "Algonquin College" },
      { id: 20, name: "Assiniboine Community College" },
      { id: 21, name: "Bishop’s University" },
      { id: 22, name: "Blue Bird Flight Academy" },
      { id: 23, name: "Bow Valley College" },
      { id: 24, name: "Brescia University College" },
      { id: 25, name: "Brescia University College" },
      { id: 26, name: "British Columbia Institute of Technology" },
      { id: 27, name: "Brock University" },
      { id: 28, name: "Cambrian at Hanson" },
      { id: 29, name: "Cambrian College" },
      { id: 30, name: "Camosun College" },
      { id: 31, name: "Canada College" },
      { id: 32, name: "Canadian College for Higher Studies" },
      { id: 33, name: "Canadian College" },
      { id: 34, name: "Canadian Film and Television Institute" },
      { id: 35, name: "Canadian Institute of Management and Technology College" },
      { id: 36, name: "Canadian Tourism College" },
      { id: 37, name: "Canadore College" },
      { id: 38, name: "Cape Breton University" },
      { id: 39, name: "Capilano University" },
      { id: 40, name: "Capilano University" },
      { id: 41, name: "CCSQ College" },
      { id: 42, name: "CDE College" },
      { id: 43, name: "CDI College" },
      { id: 44, name: "Cegep de la Gaspesie et des Iles" },
      { id: 45, name: "Centennial College" },
      { id: 46, name: "Centre for Arts and Technology" },
      { id: 47, name: "Coast Mountain College" },
      { id: 48, name: "College of New Caledonia" },
      { id: 49, name: "College of the North Atlantic" },
      { id: 50, name: "College of the Rockies" },
      { id: 51, name: "Columbia College" },
      { id: 52, name: "Commonwealth College" },
      { id: 53, name: "Concordia Continuing Education" },
      { id: 54, name: "Concordia University of Edmonton" },
      { id: 55, name: "Conestoga College" },
      { id: 56, name: "Confederation College" },
      { id: 57, name: "Coquitlam College" },
      { id: 58, name: "Crandall University" },
      { id: 59, name: "Cumberland College" },
      { id: 60, name: "Dhillon School of Business at University of Lethbridge" },
      { id: 61, name: "Durham College" },
      { id: 62, name: "European School of Esthetics" },
      { id: 63, name: "Fairleigh Dickinson University" },
      { id: 64, name: "Fanshawe College" },
      { id: 65, name: "Fleming College" },
      { id: 66, name: "George Brown College" },
      { id: 67, name: "Greystone College" },
      { id: 68, name: "Herzing College" },
      { id: 69, name: "Holland College" },
      { id: 70, name: "Holland College" },
      { id: 71, name: "Humber College" },
      { id: 72, name: "Humber Institute of Technology & Advanced Learning" },
      { id: 73, name: "IBT College" },
      { id: 74, name: "Institut Superieur d’Informatique Montreal" },
      { id: 75, name: "Inter Dec College" },
      { id: 76, name: "International College of Manitoba" },
      { id: 77, name: "John Casablancas Institute" },
      { id: 78, name: "Justice Institute of British Columbia" },
      { id: 79, name: "Keyano College" },
      { id: 80, name: "King’s University College" },
      { id: 81, name: "KLSD 8" },
      { id: 82, name: "Kwantlen Polytechnic University" },
      { id: 83, name: "La Salle College" },
      { id: 84, name: "Lakehead University" },
      { id: 85, name: "Lakeland College" },
      { id: 86, name: "Langara College" },
      { id: 87, name: "Laurentian University" },
      { id: 88, name: "LBPSB" },
      { id: 89, name: "LBPSB Pearson Electrotechnology Centre" },
      { id: 90, name: "LBPSB Pearson Electrotechnology Centre" },
      { id: 91, name: "Le Cordon Bleu Culinary Arts Institute" },
      { id: 92, name: "Lethbridge College" },
      { id: 93, name: "Liaison College" },
      { id: 94, name: "Liaison College of Culinary" },
      { id: 95, name: "Liaison College of Culinary Arts" },
      { id: 96, name: "Loyalist College" },
      { id: 97, name: "LRSD Arts and Technology Centre" },
      { id: 98, name: "M College" },
      { id: 99, name: "MacEwan University" },
      { id: 100, name: "Manitoba Institute of Trades & Technology" },
      { id: 101, name: "Matrix College" },
      { id: 102, name: "McKenzie College" },
      { id: 103, name: "Medicine Hat College" },
      { id: 104, name: "Mohawk College" },
      { id: 105, name: "Mount Allison University" },
      { id: 106, name: "Mount Royal University" },
      { id: 107, name: "Mount Saint Vincent University" },
      { id: 108, name: "New Brunswick Community College" },
      { id: 109, name: "New York Institute of Technology (NYIT)" },
      { id: 110, name: "New York Tech Vancouver" },
      { id: 111, name: "Niagara College" },
      { id: 112, name: "NorQuest College" },
      { id: 113, name: "North Island College" },
      { id: 114, name: "Northern College" },
      { id: 115, name: "Northern Lights College" },
      { id: 116, name: "Okanagan College" },
      { id: 117, name: "Olds College" },
      { id: 118, name: "Ontario College of Art and Design" },
      { id: 119, name: "Ontario Tech University" },
      { id: 120, name: "Oulton College" },
      { id: 121, name: "Parkland College" },
      { id: 122, name: "RED Academy" },
      { id: 123, name: "Red River College" },
      { id: 124, name: "Royal Crown College of Business and Technology" },
      { id: 125, name: "Red River College" },
      { id: 126, name: "Royal Roads University" },
      { id: 127, name: "Ryerson University" },
      { id: 128, name: "Saskatchewan Polytechnic" },
      { id: 129, name: "Sault College – Brampton, Ontario" },
      { id: 130, name: "SELC Career College" },
      { id: 131, name: "Selkirk College" },
      { id: 132, name: "Seneca College" },
      { id: 133, name: "Sheridan College" },
      { id: 134, name: "Southern Alberta Institute of Technology" },
      { id: 135, name: "St, Stephen’s University" },
      { id: 136, name: "St. Clair Campus" },
      { id: 137, name: "St. Francis Xavier University" },
      { id: 138, name: "St. Thomas University" },
      { id: 139, name: "Stenberg College" },
      { id: 140, name: "Thompson Rivers University" },
      { id: 141, name: "Trent University" },
      { id: 142, name: "Trinity Western University" },
      { id: 143, name: "University of Guelph" },
      { id: 144, name: "University of Manitoba" },
      { id: 145, name: "University of New Brunswick" },
      { id: 146, name: "University of Prince Edward Island" },
      { id: 147, name: "University of Regina" },
      { id: 148, name: "University of Saskatchewan" },
      { id: 149, name: "University of Saskatchewan" },
      { id: 150, name: "University of the Fraser Valley" },
      { id: 151, name: "University of Waterloo" },
      { id: 152, name: "Vancouver Community College" },
      { id: 153, name: "Western University" },
      { id: 154, name: "Wilfrid Laurier University" },
      { id: 155, name: "Yorkville University" },
      { id: 156, name: "Yorkville University" },
      { id: 157, name: "Yukon College" },
    ],
    "Australia": [
      { id: 1, name: "Amber Aviation Academy" },
      { id: 2, name: "Asia Pacific International College" },
      { id: 3, name: "Australian International Hotel School (AIHS)" },
      { id: 4, name: "Australian Maritime College" },
      { id: 5, name: "Australian Technical & Management College (ATMC)" },
      { id: 6, name: "Blue Mountains Hotel School" },
      { id: 7, name: "Box Hill Institute" },
      { id: 8, name: "Canberra Institute Of Technology" },
      { id: 9, name: "Charles Darwin University (CDU)" },
      { id: 10, name: "Charles Sturt University (All Campuses)" },
      { id: 11, name: "Chisholm Institute" },
      { id: 12, name: "CQ University Australia" },
      { id: 13, name: "Curtin University of Technology" },
      { id: 14, name: "Deakin College" },
      { id: 15, name: "Deakin University" },
      { id: 16, name: "Edith Cowan College" },
      { id: 17, name: "Edith Cowan University" },
      { id: 18, name: "Education Centre of Australia" },
      { id: 19, name: "Engineering Institute of Technology" },
      { id: 20, name: "Excelsia College" },
      { id: 21, name: "Federation University" },
      { id: 22, name: "Flinders University" },
      { id: 23, name: "Griffith College" },
      { id: 24, name: "Griffith University" },
      { id: 25, name: "Holmesglen Institute" },
      { id: 26, name: "IIBIT – Adelaide, Sydney" },
      { id: 27, name: "Institute of Health and Nursing Australia" },
      { id: 28, name: "International College of Hotel Management (ICHM)" },
      { id: 29, name: "James Cook University" },
      { id: 30, name: "James Cook University, Brisbane" },
      { id: 31, name: "Kangan Institute" },
      { id: 32, name: "Kaplan Business School" },
      { id: 33, name: "Kent Institute" },
      { id: 34, name: "La Trobe University" },
      { id: 35, name: "La Trobe University" },
      { id: 36, name: "La Trobe University, Sydney" },
      { id: 37, name: "Le Cordon Bleu" },
      { id: 38, name: "Le Cordon Bleu" },
      { id: 39, name: "Melbourne Institute of Technology (MIT)" },
      { id: 40, name: "Monash College" },
      { id: 41, name: "Monash University" },
      { id: 42, name: "Murdoch Institute of Technology" },
      { id: 43, name: "Murdoch University" },
      { id: 44, name: "RMIT University" },
      { id: 45, name: "SAE Institute" },
      { id: 46, name: "Sarina Russo Schools" },
      { id: 47, name: "Sarina Russo Schools" },
      { id: 48, name: "Southern Cross University" },
      { id: 49, name: "South Australian Institute of Business & Technology [SAIBT]" },
      { id: 50, name: "Southern Cross University Sydney Campus" },
      { id: 51, name: "St Peter Institute" },
      { id: 52, name: "State Govt Victoria-Department Of Education & Training" },
      { id: 53, name: "Swinburne University of Technology" },
      { id: 54, name: "Sydney Institute of Business & Technology" },
      { id: 55, name: "TAFE SA – Vocational Education & Training in Adelaide, South Australia" },
      { id: 56, name: "TAFE NSW" },
      { id: 57, name: "TAFE Western Australia" },
      { id: 58, name: "Taylors College" },
      { id: 59, name: "The Hotel School Sydney" },
      { id: 60, name: "Torrens University Australia" },
      { id: 61, name: "Trinity College" },
      { id: 62, name: "University Of Adelaide" },
      { id: 63, name: "University Of Adelaide" },
      { id: 64, name: "University Of Melbourne" },
      { id: 65, name: "University of New England" },
      { id: 66, name: "University of New South Wales (UNSW)" },
      { id: 67, name: "University of Newcastle" },
      { id: 68, name: "University of Queensland" },
      { id: 69, name: "University of South Australia" },
      { id: 70, name: "University of Sunshine Coast" },
      { id: 71, name: "University of Tasmania – UTAS" },
      { id: 72, name: "University of Technology Sydney- UTS" },
      { id: 73, name: "University Of Western Australia (UWA)" },
      { id: 74, name: "University of Wollongong" },
      { id: 75, name: "Victoria University" },
      { id: 76, name: "Western Sydney College" },
      { id: 77, name: "Western Sydney University" },
      { id: 78, name: "William Angliss Institute" },
    ],
    "New Zealand": [
      { id: 1, name: "AIS St. Helens Campus" },
      { id: 2, name: "ACG Group" },
      { id: 3, name: "AIS St. Helens Campus" },
      { id: 4, name: "ARA" },
      { id: 5, name: "ARA Institute of Canterbury" },
      { id: 6, name: "Aspire2 International" },
      { id: 7, name: "Auckland Institute of Studies" },
      { id: 8, name: "Auckland University of Technology" },
      { id: 9, name: "Avonmore Tertiary Institute" },
      { id: 10, name: "Bay of Plenty Polytechnic" },
      { id: 11, name: "Computer Power Plus" },
      { id: 12, name: "Cornell Institute of Business & Technology Design & Arts College [D&A]" },
      { id: 13, name: "Design and Arts College of New Zealand" },
      { id: 14, name: "Eastern Institute of Technology (EIT)" },
      { id: 15, name: "EIT" },
      { id: 16, name: "ICL Graduate Business School" },
      { id: 17, name: "International Aviation Academy of New Zealand" },
      { id: 18, name: "International College of Auckland" },
      { id: 19, name: "Le Cordon Bleu" },
      { id: 20, name: "Lincoln University" },
      { id: 21, name: "Making Futures Happen Institute" },
      { id: 22, name: "Manukau Institute of Technology" },
      { id: 23, name: "Massey University" },
      { id: 24, name: "Media Design School" },
      { id: 25, name: "NCBT College (Newton College of Business and Technology)" },
      { id: 26, name: "New Zealand Airline Academy" },
      { id: 27, name: "New Zealand Institute of Education" },
      { id: 28, name: "New Zealand Institute of Highway Technology" },
      { id: 29, name: "New Zealand Management Academies (NZMA)" },
      { id: 30, name: "New Zealand School of Education" },
      { id: 31, name: "New Zealand School of Travel, Tourism" },
      { id: 32, name: "New Zealand Tertiary College" },
      { id: 33, name: "Newton College of Business and Technology" },
      { id: 34, name: "NMIT" },
      { id: 35, name: "North Shore International Academy (NSIA)" },
      { id: 36, name: "NorthTec in Whangarei" },
      { id: 37, name: "NorthTec Institute of Technology" },
      { id: 38, name: "NZMA" },
      { id: 39, name: "Otago Polytechnic" },
      { id: 40, name: "Otago Polytechnic (Auckland Campus)" },
      { id: 41, name: "Pacific International Hotel Management School" },
      { id: 42, name: "Professional Bar and Restaurant School (PBRS)" },
      { id: 43, name: "Queenstown Resort College" },
      { id: 44, name: "Queenstown Resort College" },
      { id: 45, name: "Southern Institute of Technology (SIT)" },
      { id: 46, name: "SAE Institute (Auckland)" },
      { id: 47, name: "The University of Auckland" },
      { id: 48, name: "The University of Otago" },
      { id: 49, name: "The University of Waikato" },
      { id: 50, name: "Toi Ohomai Institute of Technology" },
      { id: 51, name: "Unitec" },
      { id: 52, name: "Universal College of Learning at NZ (UCOL)" },
      { id: 53, name: "University of Auckland" },
      { id: 54, name: "University of Canterbury" },
      { id: 55, name: "University of Canterbury International College" },
      { id: 56, name: "University of Otago" },
      { id: 57, name: "University of Waikato" },
      { id: 58, name: "UUNZ Institute of Business" },
      { id: 59, name: "Victoria University of Wellington" },
      { id: 60, name: "Waikato Institute of Technology (WINTEC)" },
      { id: 61, name: "WelTec" },
      { id: 62, name: "Western Institute of Technology at Taranaki (WITT)" },
      { id: 63, name: "Whitireia Community Polytechnic" },
      { id: 64, name: "Whitireia New Zealand" },
      { id: 65, name: "WINTEC" },
      { id: 66, name: "Yoobee School of Design" }
    ],
    "USA": [
      { id: 1, name: "Tennessee Tech University" },
      { id: 2, name: "Johns Hopkins University School of Education" },
      { id: 3, name: "Arizona State University Polytechnic" },
      { id: 4, name: "University of California, Irvine" },
      { id: 5, name: "Arizona State University Tempe" },
      { id: 6, name: "University of Central Florida" },
      { id: 7, name: "Louisiana State University" },
      { id: 8, name: "University of Utah" },
      { id: 9, name: "University of Illinois at Chicago" },
      { id: 10, name: "Colorado State University" },
      { id: 11, name: "Oregon State University" },
      { id: 12, name: "University of California, Riverside IEP" },
      { id: 13, name: "University of South Florida" },
      { id: 14, name: "University of Kansas" },
      { id: 15, name: "Washington State University" },
      { id: 16, name: "Washington State University" },
      { id: 17, name: "University of Alabama" },
      { id: 18, name: "George Mason University" },
      { id: 19, name: "University of Colorado" },
      { id: 20, name: "Florida International University" },
      { id: 21, name: "Northeastern University" },
      { id: 22, name: "University of Vermont" },
      { id: 23, name: "Auburn University" },
      { id: 24, name: "Kent State University" },
      { id: 25, name: "University of Mississippi" },
      { id: 26, name: "Baylor University" },
      { id: 27, name: "Montana State University" },
      { id: 28, name: "Saint Louis University" },
      { id: 29, name: "University of Nevada" },
      { id: 30, name: "University of Idaho" },
      { id: 31, name: "Northern Arizona University" },
      { id: 32, name: "American University" },
      { id: 33, name: "Florida Atlantic University" },
      { id: 34, name: "San Francisco State University" },
      { id: 35, name: "University of Massachusetts Boston" },
      { id: 36, name: "University of Massachusetts Lowell" },
      { id: 37, name: "Western Michigan University" },
      { id: 38, name: "San Jose State University" },
      { id: 39, name: "University of Dayton" },
      { id: 40, name: "Western Washington University" },
      { id: 41, name: "James Madison University" },
      { id: 42, name: "Clark University" },
      { id: 43, name: "Cleveland State University" },
      { id: 44, name: "Hofstra University" },
      { id: 45, name: "Wichita State University" },
      { id: 46, name: "Western Kentucky University" },
      { id: 47, name: "Pace University" },
      { id: 48, name: "Illinois State University" },
      { id: 49, name: "Marshall University" },
      { id: 50, name: "California State University Sonoma" },
      { id: 51, name: "University of the Pacific" },
      { id: 52, name: "Humboldt State University" },
      { id: 53, name: "University of the Pacific" },
      { id: 54, name: "Suffolk University" },
      { id: 55, name: "Long Island University" },
      { id: 56, name: "Adelphi University" },
      { id: 57, name: "New York Tech" },
      { id: 58, name: "California State University East Bay" },
      { id: 59, name: "Texas A&M University" },
      { id: 60, name: "Northern Kentucky University" },
      { id: 61, name: "State University of New York (SUNY) at Oswego" },
      { id: 62, name: "Murray State University" },
      { id: 63, name: "Drew University" },
      { id: 64, name: "Drew University" },
      { id: 65, name: "Mercer University" },
      { id: 66, name: "University of Hartford" },
      { id: 67, name: "Troy University" },
      { id: 68, name: "Alliant International University" },
      { id: 69, name: "California State University Monterey Bay" },
      { id: 70, name: "Webster University" },
      { id: 71, name: "Webster Southeast Missouri State University" },
      { id: 72, name: "Auburn University at Montgomery" },
      { id: 73, name: "Ohio Wesleyan University" },
      { id: 74, name: "Marymount University" },
      { id: 75, name: "University of New Haven" },
      { id: 76, name: "Western New England University" },
      { id: 77, name: "National University" },
      { id: 78, name: "Ross University School of Veterinary Medicine" },
      { id: 79, name: "Colorado State University" },
      { id: 80, name: "King's College" },
      { id: 81, name: "King's College" },
      { id: 82, name: "West Virginia State University" },
      { id: 83, name: "Ashland University" },
      { id: 84, name: "City University of Seattle" },
      { id: 85, name: "City University of Seattle" },
      { id: 86, name: "Manhattanville College" },
      { id: 87, name: "Alvernia University" },
      { id: 88, name: "SUNY Polytechnic Institute" },
      { id: 89, name: "Colorado Mesa University" },
      { id: 90, name: "Southern New Hampshire University" },
      { id: 91, name: "Lycoming College" },
      { id: 92, name: "Chatham University" },
      { id: 93, name: "Mercy College" },
      { id: 94, name: "Metropolitan State University of Denver" },
      { id: 95, name: "Santa Monica College" },
      { id: 96, name: "Capital University" },
      { id: 97, name: "Lipscomb University" },
      { id: 98, name: "Lynn University" },
      { id: 99, name: "Concordia University" },
      { id: 100, name: "Full Sail University" },
      { id: 101, name: "Valencia College" },
      { id: 102, name: "Husson University" },
      { id: 103, name: "St. Francis University" },
      { id: 104, name: "Virginia Wesleyan University" },
      { id: 105, name: "New York Film Academy" },
      { id: 106, name: "Point Park University" },
      { id: 107, name: "Rivier University" },
      { id: 108, name: "Shoreline Community College" },
      { id: 109, name: "Seattle Central College" },
      { id: 110, name: "Trine University" },
      { id: 111, name: "Shorter University" },
      { id: 112, name: "Elgin Community College" },
      { id: 113, name: "Chemeketa Community College" },
      { id: 114, name: "Oregon State University" },
      { id: 115, name: "Monroe College" },
      { id: 116, name: "Tacoma Community College" },
      { id: 117, name: "Northeast Wisconsin Technical College" },
      { id: 118, name: "Freed Hardeman University" },
      { id: 119, name: "San Mateo Colleges" },
      { id: 120, name: "San Mateo Colleges" },
      { id: 121, name: "College of San Mateo" },
      { id: 122, name: "South Puget Sound Community College" },
      { id: 123, name: "San Mateo Colleges" },
      { id: 124, name: "SUNY Polytechnic Institute" },
      { id: 125, name: "Mission College" },
      { id: 126, name: "University Bridge" },
      { id: 127, name: "Queens College of The City University of New York" },
      { id: 128, name: "Walla Walla Community College" },
      { id: 129, name: "Atlantis University" },
      { id: 130, name: "LIM College" },
      { id: 131, name: "Evans Library and Learning Commons" },
      { id: 132, name: "Westcliff University" },
      { id: 133, name: "Marymount California University" },
      { id: 134, name: "American University of the Caribbean School of Medicine" },
      { id: 135, name: "Hancock International College" },
      { id: 136, name: "East Coast Polytechnic Institute University" },
      { id: 137, name: "Florida Polytechnic University" },
      { id: 138, name: "IGlobal University" },
      { id: 139, name: "Sofia University" },
      { id: 140, name: "Christian Culinary Academy" },
      { id: 141, name: "East Coast Polytechnic Institute University" },

    ],
    "Cyprus": [
      { id: 1, name: "ALEXANDER COLLEGE" },
      { id: 2, name: "C.D.A. College" },
      { id: 3, name: "Casa College" },
      { id: 4, name: "College of Business Studies" },
      { id: 5, name: "College of Tourism and Hotel Management" },
      { id: 6, name: "INTERNAPA COLLEGE" },
      { id: 7, name: "Ledra College" },
      { id: 8, name: "Philips College" },

    ],
    "Finland": [
      { id: 1, name: "JAMK University" },
    ],
    "France": [
      { id: 1, name: "American Business School (ABS)" },
      { id: 2, name: "Atelier Chardon Savard" },
      { id: 3, name: "Audencia Business School" },
      { id: 4, name: "CASS" },
      { id: 5, name: "CEFAM" },
      { id: 6, name: "College De Paris" },
      { id: 7, name: "Corus Florent" },
      { id: 8, name: "Ducasse Education" },
      { id: 9, name: "Ecole Centrale de Lille" },
      { id: 10, name: "Ecole Centrale de Nantes" },
      { id: 11, name: "EDC Business School" },
      { id: 12, name: "EICAR" },
      { id: 13, name: "EISTI" },
      { id: 14, name: "EM Normandie Business School" },
      { id: 15, name: "ENAC" },
      { id: 16, name: "EPITA Graduate School of Computer Science" },
      { id: 17, name: "EPSI" },
      { id: 18, name: "ESAIP Graduate School of Engineering" },
      { id: 19, name: "ESAM" },
      { id: 20, name: "ESC Clermont" },
      { id: 21, name: "ESGCI" },
      { id: 22, name: "ESLSCA" },
      { id: 23, name: "ESTACA Engineering School" },
      { id: 24, name: "Eurecom Graduate School" },
      { id: 25, name: "ICD" },
      { id: 26, name: "IDRAC Business School" },
      { id: 27, name: "IEFT" },
      { id: 28, name: "IESA" },
      { id: 29, name: "IFAG School of Management" },
      { id: 30, name: "IGS RH" },
      { id: 31, name: "IMT Mines - Ales" },
      { id: 32, name: "IMT Mines-Albi Carmux Engineering School" },
      { id: 33, name: "IMT-Atlantique" },
      { id: 34, name: "INP" },
      { id: 35, name: "INP Toulouse Engineering School" },
      { id: 36, name: "Institut Culinaire de France" },
      { id: 37, name: "Institut Mines - Telecom Business School (IMT)" },
      { id: 38, name: "IPAG Business School" },
      { id: 39, name: "ISC Paris" },
      { id: 40, name: "ISEP Engineering Graduate School" },
      { id: 41, name: "Kedge Business School" },
      { id: 42, name: "L'Ecole de Design" },
      { id: 43, name: "L'école de Design Nantes Atlantique" },
      { id: 44, name: "L'École Supérieure de Tourisme" },
      { id: 45, name: "La Rochelle Business School" },
      { id: 46, name: "LISAA" },
      { id: 47, name: "Montpellier Business School" },
      { id: 48, name: "Neoma Business School" },
      { id: 49, name: "Paris School of Business (PSB)" },
      { id: 50, name: "Pole Leonardo De Vinci" },
      { id: 51, name: "Rennes School of Business" },
      { id: 52, name: "SHG Nice- International Hospitality and Business School" },
      { id: 53, name: "SHG Strasbourg - International Hospitality and Business School" },
      { id: 54, name: "Skema Business School" },
      { id: 55, name: "South Champagne Business School (SCBS)" },
      { id: 56, name: "Speos Paris Photographic Institute" },
      { id: 57, name: "Sports Management School" },
      { id: 58, name: "Strate School of Design" },
      { id: 59, name: "Université Catholique de l'Ouest" },
      { id: 60, name: "Vatel Hotel and Tourism Business School" },
      { id: 61, name: "Wes Sup College" },

    ],
    "Denmark": [
      { id: 1, name: "Absalon University College, Kalundborg" },
      { id: 2, name: "Business Academy of Aarhus" },
      { id: 3, name: "Dania University of Applied Science" },
      { id: 4, name: "International Business Academy (IBA), Kolding" },
      { id: 5, name: "VIA University of Applied Science" },
      { id: 6, name: "Zealand Institute of Business and Technology" },
    ],
    "Germany": [
      { id: 1, name: "Berlin School of Business & Innovation (BSBI)" },
      { id: 2, name: "GISMA Business School" },
      { id: 3, name: "IUBH" },
      { id: 4, name: "New European College (NEC)" },
      { id: 5, name: "University of Applied Science" },
    ],
    "Greece": [
      { id: 1, name: "AAS College" },
      { id: 2, name: "Hellenic American University" },
    ],
    "Ireland": [
      { id: 1, name: "Athlone Institute of Technology" },
      { id: 2, name: "Atlantic Aviation Institute (AAI)" },
      { id: 3, name: "Cork Institute of Technology" },
      { id: 4, name: "Dublin Business School (DBS)" },
      { id: 5, name: "Dublin City University (DCU)" },
      { id: 6, name: "Dublin Institute of Technology (DIT)" },
      { id: 7, name: "Dundalk Institute of Technology" },
      { id: 8, name: "Galway Mayo Institute of Technology" },
      { id: 9, name: "Griffith College" },
      { id: 10, name: "Institute of Art, Design and Technology" },
      { id: 11, name: "Institute of Technology Carlow" },
      { id: 12, name: "Institute of Technology Tralee" },
      { id: 13, name: "IT Sligo" },
      { id: 14, name: "Letterkenny Institute of Technology" },
      { id: 15, name: "Limerick Institute of Technology" },
      { id: 16, name: "Maynooth University (MU)" },
      { id: 17, name: "National College of Ireland" },
      { id: 18, name: "National University of Ireland Galway" },
      { id: 19, name: "Shannon College of Hotel Management" },
      { id: 20, name: "The Technological University of Dublin" },
      { id: 21, name: "Trinity College Dublin" },
      { id: 22, name: "TU Dublin (Blanchardstown)" },
      { id: 23, name: "TU Dublin (DIT)" },
      { id: 24, name: "University College Cork" },
      { id: 25, name: "University College Dublin" },
      { id: 26, name: "University of Limerick" },
      { id: 27, name: "Waterford Institute of Technology" }

    ],
    "Malta": [
      { id: 1, name: "Advenio eAcademy" },
      { id: 2, name: "American University of Malta (AUM)" },
      { id: 3, name: "Chartered Institute of Logistics & Transport - CILT" },
      { id: 4, name: "EEC-ITIS Malta Tourism and Languages Institute" },
      { id: 5, name: "Global College Malta" },
      { id: 6, name: "Institute of Tourism Studies - ITS" },
      { id: 7, name: "Learn Key Institute" },
      { id: 8, name: "London School of Commerce - LSC" },
      { id: 9, name: "Malta College of Arts, Science and Technology (MCAST)" },
      { id: 10, name: "MX Institute" },
      { id: 11, name: "The University of Malta" }
    ],
    "Malaysia": [
      { id: 1, name: "College KAGC Malaysia" }
    ],
    "Italy": [
      { id: 1, name: "Accademia Della Moda" },
      { id: 2, name: "Poli Design" },
      { id: 3, name: "Rome Business School" },
      { id: 4, name: "Vesuvio International School of Hospitality (VISH)" }
    ],
    "Lithuania": [
      { id: 1, name: "Vilnius University" }
    ],
    "Netherlands": [
      { id: 1, name: "Wittenborg University of Applied Science" },
      { id: 2, name: "Wittenborg University of Applied Science" }
    ],
    "Latvia": [
      { id: 1, name: "Eka The University of Economics and Culture" },
      { id: 2, name: "LIEPAJA University" },
      { id: 3, name: "Riga Strandins University (RSU)" },
      { id: 4, name: "Riga Technical University (RTU)" },
      { id: 5, name: "Riga Technical University (RTU)" },
      { id: 6, name: "Riseba University" },
      { id: 7, name: "Turiba University" }
    ],
    "Poland": [
      { id: 1, name: "Bialystok University of Technology" },
      { id: 2, name: "College of Tourism and Ecology (WSTiE)" },
      { id: 3, name: "Cracow University of Technology (CUT)" },
      { id: 4, name: "Cracow University of Technology" },
      { id: 5, name: "Lublin University of Technology (LUT)" },
      { id: 6, name: "Maria Curie Sklodowska (UMCS)" },
      { id: 7, name: "Olsztyn University" },
      { id: 8, name: "Opole University of Technology" },
      { id: 9, name: "Polish-Japanese Academy of Information Technology" },
      { id: 10, name: "Silesian University of Technology (SUT)" },
      { id: 11, name: "UnitedSky" },
      { id: 12, name: "University College of Enterprise and Administration (WSPA)" },
      { id: 13, name: "University of Economics and Human Sciences (UFM / UEHS)" },
      { id: 14, name: "University of Economics in Katowice" },
      { id: 15, name: "University of Euroregional Economy (WSGE)" },
      { id: 16, name: "University of Life Science in Lublin" },
      { id: 17, name: "Vincent Pol University" },
      { id: 18, name: "Vistula University" },
      { id: 19, name: "Warsaw Management University (WMU/WSM)" },
      { id: 20, name: "Warsaw University of Life Sciences-SGGW" },
      { id: 21, name: "Warsaw University of Life Sciences-SGGW" },
      { id: 22, name: "Warsaw University of Technology (WUT)" },
      { id: 23, name: "Warsaw University of Technology (WUT)" },
      { id: 24, name: "Warsaw University of Technology (WUT)" },
      { id: 25, name: "Wroclaw University of Environmental and Life Sciences (WULS)" },
      { id: 26, name: "Wroclaw University of Environmental and Life Sciences (WULS)" }
    ],
    "Switzerland": [],
    "Spain": [],
    "Singapore": [],
  }

  selectedCountry = "United Kingdom";
  countryList: any;
  colleges: any;
  seachText = "";
  searchForm: FormGroup;
  constructor(private fb: FormBuilder) {
    this.countryList = Object.keys(this.collegeList);
    this.colleges = this.collegeList[this.selectedCountry];
    this.searchForm = this.fb.group({
      search: ''
    })
  }

  ngOnInit(): void {
    this.searchForm.valueChanges.subscribe((data: any) => {
      console.log(data);
      this.colleges = this.collegeList[this.selectedCountry].filter((item) => {
        return item.name.toLowerCase().includes(data.search.toLowerCase()) ? item : '';

      })
    })
  }

  getColleges(country: string) {
    this.selectedCountry = country;
    this.colleges = this.collegeList[this.selectedCountry];
  }


}
